/* #undef ENABLE_BITMAP_ALLOCATOR */
/* #undef ENABLE_BOOST_FAST_POOL_ALLOCATOR */
/* #undef ENABLE_BOOST_POOL_ALLOCATOR */
/* #undef ENABLE_DEBUG_ALLOCATOR */
/* #undef ENABLE_MT_ALLOCATOR */
/* #undef ENABLE_NEW_ALLOCATOR */
/* #undef ENABLE_POOL_ALLOCATOR */
/* #undef ENABLE_TBB_ALLOCATOR */
/* #undef HAVE_ALLOCATOR_CONFIG */
/* #undef HAVE_BOOST_SHARED_PTR */
/* #undef HAVE_STD_SHARED_PTR */
#define HAVE_STD_TR1_SHARED_PTR 1
/* #undef HAVE_BOOST */
/* #undef HAVE_BOOST_SHARED_PTR */
/* #undef HAVE_TBB */
/* #undef HAVE_SSL */
/* #undef HAVE_EMX */
/* #undef HAVE_VMA */
/* #undef HAVE_SYSTEMTAP */
/* #undef HAVE_STD_UNIQUE_PTR */
/* #undef ENABLE_SSO */
#define ENABLE_THROW_DECL 1
/* #undef ENABLE_FLAT_FIELDMAP */
/* #undef ENABLE_RELAXED_ORDERING */
/* #undef ENABLE_DICTIONARY_FIELD_ORDER */
